### ISSUE TITLE
不换号空格（NBSP）问题

### ISSUE THREAD

**Issue by plus7wist** [88250/lute-pdf#2]
文章在：<https://hacpai.com/article/1593502506573>，生成的 pdf 在：https://b3logfile.com/pdf/article/1593502506573.pdf。

这篇文章如果有特殊性，那么就是使用了比较多的分割符号（`---`）。但另一篇类似的文章：https://hacpai.com/article/1593157956376 生成的结果（虽然也乱七八糟）没有吞掉大量汉字。

**Comment by 88250** [comment]
感谢反馈，已经修复。
